version: "3" # 파일 규격 버전
services: # 이 항목 밑에 실행하려는 컨테이너 들을 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  ably-db: # 서비스 명
      image: mysql
      restart: always
      container_name: ably_mysql # 컨테이너 이름 설정
      ports:
        - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
      environment: # -e 옵션
        - MYSQL_DATABASE=ably
        - MYSQL_USER=kjkim
        - MYSQL_PASSWORD=kj123!@#
        - MYSQL_ROOT_PASSWORD=kj123!@#  # MYSQL 패스워드 설정 옵션
        - TZ=Asia/Seouli
      command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
      volumes:
        - /home/ubuntu/ably-externship/mysql-data:/var/lib/mysql
  ably-mission:
      image: ably-mission
      ports:
        - "80:8000"
      # restart: always
      container_name: ably-mission
      depends_on:
       -  ably-db